version: '2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "3000:3000"
    volumes:
      - /tmp/badger:/tmp/badger
    environment:
      DB_PATH: /tmp/badger
      PORT: "1234"
      ENV: development
      DARE_PASSWORD: password
      DARE_SALT: salt
      JWT_SECRET: jwt_secret
